### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by patric-eberle** [alexlafroscia/ember-cli-polyfill-io#1]
Ember 2.7.3.

I'm unable to install your addon with `ember install ember-cli-polyfill-io`. The following error is given:

```
Installed packages for tooling via npm.
Unexpected token =
SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/patriceberle/Documents/projects/ivoclar/order-manager-ui/node_modules/ember-cli-polyfill-io/index.js:4:18)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
```

I tried on two different projects and gotten the same error.

**Comment by alexlafroscia** [comment]
Node version?

**Comment by patric-eberle** [comment]
Node: 5.6.0
npm 3.6.0

**Comment by alexlafroscia** [comment]
Hmm, could be an issue with your version of Node. I did development against 6.7.0, maybe I use a feature that isn't Node 5.X compliant?

**Comment by alexlafroscia** [comment]
Hmm, so the error seems to correspond to [this line here](https://github.com/alexlafroscia/ember-cli-polyfill-io/blob/bdb2c5071a67015a7837904da91bc47677001985/index.js#L4). It seems like your node version should be fine with using `const` but I can't imagine what else the issue would be.  Are you able to use `const` the Node REPL on your machine?

**Comment by patric-eberle** [comment]
Sorry, I don't know how I should test this REPL. I'm not too familiar with Node ;) - Still I found out that:
- When raising the Node version to 7.4.0 the installation works
- When installing with `npm` instead of `ember` it works
- The problem already occurs on a newly created Ember project

**Comment by alexlafroscia** [comment]
> When raising the Node version to 7.4.0 the installation works

Cool, so we know it's a Node version error

> When installing with npm instead of ember it works

On which version of node? Are you saying that 

```bash
npm install --save-dev ember-cli-polyfill-io
```

works on 5.4, but

```bash
ember install ember-cli-polyfill-io
```

does not?  Or that

```bash
npm install --save-dev ember-cli-polyfill-io
```

works on 7.4, but

```bash
ember install ember-cli-polyfill-io
```

does not?  Either way, there should be no difference here -- `ember install` imply runs NPM under the hood, and there are no blueprints to execute (which would happen with an `ember install` but not an `npm install`). I'd definitely like to get to the bottom of why it works with one tool and not the other.

> The problem already occurs on a newly created Ember project

I'm not sure what you mean here, can you clarify?

**Comment by patric-eberle** [comment]
```npm install --save-dev ember-cli-polyfill-io``` works on 5.6 and 7.4. But `ember install` only on 7.4.

By

> The problem already occurs on a newly created Ember project

I mean, that at first I only tried to add your addon to an existing project, and was unsure, if maybe some other addons caused conflicts or so. But that seems not to be the case.

**Comment by alexlafroscia** [comment]
I see... Very strange that it doesn't work with `ember install` on 5.6. I'll try it out this weekend and see if I can get to the bottom of this.

**Comment by alexlafroscia** [comment]
I was able to reproduce the issues you're seeing. The problem is definitely that the add-on uses node features that aren't supported in Node 5.6.0.

It shouldn't be too hard to just use the old JS features, so I'm going to try to roll the minimum supported Node version back to 4.X or something, whatever the CLI uses right now.

**Comment by alexlafroscia** [comment]
Try installing version `1.2.0` of the add-on, it should work for you  now.

**Comment by patric-eberle** [comment]
@alexlafroscia works! thx
